### ISSUE TITLE
Clarify handling of duplicate messages

### ISSUE THREAD

**Issue by rohan-wire** [bifurcation/ietf-mimi-protocol#54]

**Comment by bifurcation** [comment]
DT call 2024-02-28:
* Problem: Hub might think that a `/notify` failed and retry, recipient needs a way to dedup
* Alternatives:
    * Explicit transaction ID set by hub
    * Hash of `/notify` request body (=> no need for an explicit identifier in protocol)
* Either way, recipient needs to keep a strike list of things it has already seen
* Proposal: Add text that says you can dedup by hash, add discussion of tradeoffs
* @bifurcation to make a PR on this

**Comment by raphaelrobert** [comment]
Adding the arguments against using hashes that were discussed in the DT call 2024-02-28:
 - Hashes introduce the requirement that message content must be unique. This blurs the abstraction lines between the protocol levels. E.g. it might be fine to send the exact same message repeatedly at a higher level of the protocol, but those message would be be delivered because the transport layer considers them to be duplicates.
 - Messages that are retransmitted must now always be identical. This requirement is probably easier to meet than the first one, but it's there nonetheless.

**Comment by rohanmahy** [comment]
Closing with PR #60 merged.
